version: 2

updates:
  # Maintain dependencies for terraform modules
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
