name: Checkov
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - ./
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
    steps:
    - uses: dasmeta/reusable-actions-workflows/checkov@4.1.0
      with:
        fetch-depth: 0
        directory: ${{ matrix.path }}
