name: TFSEC
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-tfsec:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      checks: write
      issues: write
      packages: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
    - uses: dasmeta/reusable-actions-workflows/tfsec@main
      with:
        fetch-depth: 0
    continue-on-error: true
